name: Django CI/CD Pipeline

# to trigger github actions eg when the mian branch is pushed to 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository #clones the repo onto the runner machine (VM) for the workflow to run
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: latest

      - name: Install Dependencies #install the project dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest 
    needs: build #depends on the completion of the build job

    steps:
      - name: Apply Migrations
        run: python manage.py migrate #capturing any changes in the models for postgres

      - name: Run Tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-heroku-app-name

      - name: Deploy to Heroku
        run: git push heroku main

      - name: Run Django Collectstatic
        run: python manage.py collectstatic --noinput

# Additional steps for environment variables and PostgreSQL setup if needed
