# Generated by Django 4.2.4 on 2023-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('lounge', 'Lounge'), ('kitchen', 'Kitchen'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('other', 'Other')], max_length=250)),
                ('is_healthy', models.BooleanField()),
            ],
        ),
    ]
