# Generated by Django 4.2.4 on 2023-08-14 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_plantcare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcare',
            name='date',
            field=models.DateField(verbose_name='watering date'),
        ),
        migrations.AlterField(
            model_name='plantcare',
            name='water_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
