# Generated by Django 4.2.4 on 2023-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_plantcare_date_alter_plantcare_water_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='plantcare',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='plants',
            name='carers',
            field=models.ManyToManyField(to='main_app.carer'),
        ),
    ]
