# Generated by Django 5.0 on 2023-12-19 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_carer_alter_plantcare_options_plants_carers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('carer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.carer')),
            ],
        ),
    ]
