name: Django CI/CD Pipeline

# to trigger github actions eg when the main branch is pushed to 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set environment variable
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

    - name: Run Django migrations and tests
      run: |
        python manage.py migrate
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build  #depends on all test passing

    steps:
      - name: Set up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: foliageanalyst

      - name: Deploy to Heroku
        run: git push heroku main

      - name: Run Django Collectstatic
        run: python3 manage.py collectstatic --noinput

      - name: Run Migrations on Heroku
        run: |
          heroku run python manage.py migrate --app foliageanalyst
